

                      term  ::=  "𝘦𝘮𝘱𝘵𝘺"<NO_WHITESPACE>"("")"

                              |  "𝘪𝘯𝘴𝘦𝘳𝘵"<NO_WHITESPACE>"(" argument "," argument ")"

                              |  "𝘥𝘦𝘭𝘦𝘵𝘦"<NO_WHITESPACE>"(" argument "," argument ")" 

                              ;

