

                      term  ::=  unaryFunction

                              |  operation 

                              ;


             unaryFunction  ::=  argument<NO_WHITESPACE>"(" argument ")" ;


                 operation  ::=  "empty"<NO_WHITESPACE>"("<NO_WHITESPACE>")"

                              |  "insert"<NO_WHITESPACE>"(" argument "," argument ")"

                              |  "delete"<NO_WHITESPACE>"(" argument "," argument ")" 

                              ;

